#! /bin/bash

# Installation for 18.04 LTS (bionic)

sudo apt-get update
sudo apt-get upgrade -y

sudo wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -

sudo echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongod$

sudo apt-get update

sudo apt-get install -y mongodb-org

sudo apt-get install -y python-pymongo

sudo service mongod start

echo "MongoDB is ready!"



